# permissions for end users to edit helmcharts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: plugin-helm-chart
    app.kubernetes.io/managed-by: kustomize
  name: helmchart-editor-role
rules:
- apiGroups:
  - plugin-helm-chart.kloudlite.github.com
  resources:
  - helmcharts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plugin-helm-chart.kloudlite.github.com
  resources:
  - helmcharts/status
  verbs:
  - get
