apiVersion: plugin-helm-chart.kloudlite.github.com/v1
kind: HelmChart
metadata:
  labels:
    app.kubernetes.io/name: plugin-helm-chart
    app.kubernetes.io/managed-by: kustomize
  name: helmchart-sample
spec:
  # TODO(user): Add fields here
