# vim: set ft=dockerfile:
FROM alpine:latest AS builder
RUN apk add nix
WORKDIR /app

# Mount your local /nix/store for cache re-use
RUN --mount=type=cache,target=/nix,from=nixos/nix:2.21.1,source=/nix \
  --mount=type=cache,from=project-root,source=flake.nix,target=flake.nix \
  --mount=type=cache,from=project-root,source=flake.lock,target=flake.lock \
  --mount=type=cache,target=/root/.cache \
  <<EOF
  nix \
    --extra-experimental-features "nix-command flakes" \
    --option filter-syscalls false \
    build .#helm-job-runner --out-link /tmp/output/result
  
  mkdir -p /tmp/nix-store-closure
  cp -R $(nix-store -qR /tmp/output/result) /tmp/nix-store-closure
EOF

FROM scratch

WORKDIR /app
COPY --from=builder /tmp/nix-store-closure /nix/store
COPY --from=builder /tmp/output/ /app/

ENV PATH=/app/result/bin
