# vim: set ft=dockerfile:
FROM alpine:latest AS builder
RUN apk add nix
WORKDIR /app

RUN --mount=type=cache,from=project-root,source=flake.nix,target=flake.nix \
  --mount=type=cache,from=project-root,source=flake.lock,target=flake.lock \
  <<EOF
nix \
  --extra-experimental-features "nix-command flakes" \
  --option filter-syscalls false \
  build .#helm-job-runner --out-link /tmp/output/result

mkdir -p /tmp/nix-store-closure
cp -R $(nix-store -qR /tmp/output/result) /tmp/nix-store-closure
EOF

FROM gcr.io/distroless/static
COPY --from=builder /tmp/nix-store-closure /nix/store
USER nonroot:nonroot
COPY --from=builder --chown=nonroot:nonroot /tmp/output/ /app/
ENV PATH=/app/result/bin
