name: Release

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        type: string
        description: "image_tag"
        required: true
        default: ""

  push:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: plugin/helm-charts image
    steps:
      - uses: actions/checkout@v4

      - uses: kloudlite/actions/setup-cache-go@v1
        with:
          cache_key: "run-${{ matrix.platform }}-${{ matrix.arch }}"
          working_directory: .

      - uses: kloudlite/actions/generate-image-tag@v1

      - uses: kloudlite/actions/setup-nix-cachix@v1
        with:
          flake_lock: "./flake.lock"
          nix_develop_arguments: ".#default"
          cachix_cache_name: ${{ secrets.CACHIX_CACHE_NAME }}
          cachix_auth_token:  ${{ secrets.CACHIX_AUTH_TOKEN }}

      - uses: kloudlite/actions/setup-docker@v1
        with:
          docker_registry: "ghcr.io"
          docker_username: ${{ github.actor }}
          docker_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Binary
        shell: bash
        env:
          IMAGE: "ghcr.io/${{ github.repository }}:$IMAGE_TAG"
        run: |+
          run build image=$IMAGE
