name: building api with nix

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        type: string
        description: "image_tag"
        required: true
        default: "latest"

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: ${{ matrix.images.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: kloudlite/actions/setup-nix-cachix@v1
        with:
          flake_lock: "./flake.lock"
          nix_develop_arguments: ".#default"
          cachix_cache_name: ${{secrets.CACHIX_CACHE_NAME }}
          cachix_auth_token:  ${{ secrets.CACHIX_AUTH_TOKEN }}
