# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: plugin-helm-chart
---

# Service Account RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plugin-helm-chart
  namespace: plugin-helm-chart

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plugin-helm-chart-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: plugin-helm-chart
    namespace: plugin-helm-chart
---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: plugin-helm-chart
  name: plugin-helm-chart
  namespace: plugin-helm-chart
spec:
  replicas: 1
  selector:
    matchLabels: &match-labels
      control-plane: plugin-helm-chart
  template:
    metadata:
      labels: *match-labels
    spec:
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          image: ghcr.io/kloudlite/plugin-helm-chart/controller:v1.0.0
          imagePullPolicy: Always
          env:
            - name: MAX_CONCURRENT_RECONCILES
              value: "5"

            - name: HELM_JOB_RUNNER_IMAGE
              value: "ghcr.io/kloudlite/plugin-helm-chart/helm-job-runner:v1.0.0"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 # nonroot user from gcr.io/distroless/static:nonroot image
        runAsGroup: 65532 # nonroot group from gcr.io/distroless/static:nonroot image
        allowPrivilegeEscalation: false
      serviceAccountName: "plugin-helm-chart"
      terminationGracePeriodSeconds: 10

